### ISSUE TITLE
Convert to source distribution

### ISSUE THREAD

**Issue by andrewjl-mux** [muxinc/mux-stats-sdk-avplayer#199]
```[tasklist]
### Tasks
- [ ] Convert Swift Package Manager Package.swift to use source-based targets
- [ ] Convert Cocoapod podspec to install source files
- [ ] Graceful Carthage support for source-based SDK
```

**Comment by gabors** [comment]
How is this one coming along?

**Comment by andrewjl-mux** [comment]
Hey @gabors, no timeline to share yet on when it'll be available. We'll keep this issue posted with any progress. Thank you for checking in!

**Comment by andrewjl-mux** [comment]
Hey @gabors! Some good news, there's a PR [here](https://github.com/muxinc/mux-stats-sdk-avplayer/pull/215) with what should be most of the required changes to remove `MUXSDKStats.xcframework`. There's still some more testing to be done so the PR is a draft for now.

**Comment by gabors** [comment]
Hi @andrewjl-mux 
How is that 4.0.0 release coming along?

**Comment by CFKevinRef** [comment]
Releasing from source as of [v4.6.0](https://github.com/muxinc/mux-stats-sdk-avplayer/releases/tag/v4.6.0)
